version: "3.1"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-airflow}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-airflow}
      POSTGRES_DB: ${POSTGRES_DB:-airflow}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    networks:
      - autoapply-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: airflow
      MONGO_INITDB_ROOT_PASSWORD: airflow
      MONGO_INITDB_DATABASE: autoapply
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - autoapply-network

  airflow-webserver:
    image: apache/airflow:2.7.0
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY:-}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:-true}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES:-false}
      - AIRFLOW__API__AUTH_BACKENDS=${AIRFLOW__API__AUTH_BACKENDS:-airflow.api.auth.backend.basic_auth}
      - AIRFLOW__CORE__MONGODB_CONN=mongodb://${MONGODB_USER:-airflow}:${MONGODB_PASSWORD:-airflow}@mongodb:27017/${MONGODB_NAME:-jobsDB}
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__PLUGINS_FOLDER=/opt/airflow/plugins
      - AIRFLOW__CORE__LOGS_FOLDER=/opt/airflow/logs
      - AIRFLOW__WEBSERVER__SECRET_KEY=your_secret_key_here
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=true
      - AIRFLOW__WEBSERVER__WORKERS=4
      - AIRFLOW__WEBSERVER__WORKER_CLASS=sync
      - AIRFLOW__WEBSERVER__ACCESS_LOGFORMAT="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
      - AIRFLOW__WEBSERVER__ERROR_LOGFORMAT="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    volumes:
      - ./src:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - autoapply-network

  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER:-airflow}:${POSTGRES_PASSWORD:-airflow}@postgres/${POSTGRES_DB:-airflow}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY:-}
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:-true}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES:-false}
      - AIRFLOW__API__AUTH_BACKENDS=${AIRFLOW__API__AUTH_BACKENDS:-airflow.api.auth.backend.basic_auth}
      - AIRFLOW__CORE__MONGODB_CONN=mongodb://${MONGODB_USER:-airflow}:${MONGODB_PASSWORD:-airflow}@mongodb:27017/${MONGODB_NAME:-jobsDB}
      - AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
      - AIRFLOW__CORE__PLUGINS_FOLDER=/opt/airflow/plugins
      - AIRFLOW__CORE__LOGS_FOLDER=/opt/airflow/logs
    volumes:
      - ./src:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    command: scheduler
    healthcheck:
      test:
        [
          "CMD-SHELL",
          'airflow jobs check --job-type SchedulerJob --hostname "$${HOSTNAME}"',
        ]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    networks:
      - autoapply-network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
      - ./data:/app/data
      - ./resume:/resume # fixed the resume path
      - ./output:/output # added the output path for final customizaed resume
      - ./parquet:/app/parquet
    environment:
      - MONGODB_URI=mongodb://airflow:airflow@mongodb:27017/autoapply?authSource=admin
      - MONGODB_DB=autoapply
      - MONGODB_COLLECTION=resumes
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - ENVIRONMENT=${ENVIRONMENT:-development}
      - DEBUG=${DEBUG:-True}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      mongodb:
        condition: service_healthy
    restart: always
    networks:
      - autoapply-network

  sonar-scanner:
    image: sonarsource/sonar-scanner-cli:latest
    container_name: sonar-scanner
    volumes:
      - ./:/usr/src
    working_dir: /usr/src
    environment:
      SONAR_HOST_URL: "https://sonarqube.nunchisolucoes.com"
      # Using just token to avoid warnings
      SONAR_TOKEN: "${SONAR_TOKEN}"
      SONAR_PROJECT_KEY: "${SONAR_PROJECT_KEY}"
    networks:
      - autoapply-network
    # Use our custom script with timeout
    entrypoint: ["sh", "/usr/src/run-sonar.sh"]

networks:
  autoapply-network:
    driver: bridge

volumes:
  postgres-db-volume:
  mongodb-data:
