# Configuración de SonarQube
sonar.projectKey=JobMate
sonar.projectName=Project AutoApply Branch Dev
sonar.host.url=https://sonarqube.nunchisolucoes.com
sonar.login=${SONAR_TOKEN}

# Configuración de código fuente
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/tests/**,**/*.md

