[api_keys]
GEMINI_API_KEY = "AIzaSyDF25GkMEGSO8vSYCNOWtjjGKdtxTA-gdg"

[database]
MONGODB_URI = "mongodb://airflow:airflow@mongodb:27017/autoapply?authSource=admin"
MONGODB_DB = "autoapply"
MONGODB_COLLECTION = "resumes"