"""Add bio, skills, and experience_level fields to users table

Revision ID: f1a2b3c4d5e6
Revises: c57186012b4d
Create Date: 2025-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'c57186012b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('experience_level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('experience_level')
        batch_op.drop_column('skills')
        batch_op.drop_column('bio')
    # ### end Alembic commands ### 