"""Add bio, skills, experience_level to User model

Revision ID: c57186012b4d
Revises: c7c02ef66411
Create Date: 2025-07-26 12:41:08.333654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c57186012b4d'
down_revision = 'c7c02ef66411'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_apply_settings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    op.create_table('auto_apply_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('max_daily', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=False),
    sa.Column('min_match_score', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=False),
    sa.Column('cover_letter_type', sa.VARCHAR(length=20), server_default=sa.text("'''generic'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('preferred_job_types', sa.VARCHAR(length=20), server_default=sa.text("'''all'''::character varying"), autoincrement=False, nullable=False),
    sa.Column('additional_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('today_application_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint("cover_letter_type::text = ANY (ARRAY['none'::character varying, 'generic'::character varying, 'custom'::character varying]::text[])", name=op.f('check_cover_letter_type')),
    sa.CheckConstraint("preferred_job_types::text = ANY (ARRAY['all'::character varying, 'full_time'::character varying, 'remote'::character varying, 'full_time_remote'::character varying]::text[])", name=op.f('check_preferred_job_types')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('auto_apply_settings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('auto_apply_settings_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('auto_apply_settings_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
