"""Add users table and initial models

Revision ID: cddba9a77f3b
Revises: 
Create Date: 2025-06-27 11:45:33.207349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cddba9a77f3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.Enum('applicant', 'recruiter', name='user_types'), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruiter_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('benefits', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('preferred_skills', sa.JSON(), nullable=True),
    sa.Column('experience_level', sa.Enum('entry', 'junior', 'mid', 'senior', 'lead', 'executive', name='job_experience_level'), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('max_experience_years', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.Enum('high_school', 'college', 'bachelor', 'master', 'phd', 'certification', name='education_level'), nullable=True),
    sa.Column('education_field', sa.String(length=100), nullable=True),
    sa.Column('certifications_required', sa.JSON(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'temporary', 'internship', 'co_op', name='employment_type'), nullable=False),
    sa.Column('contract_duration', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('remote_type', sa.Enum('onsite', 'remote', 'hybrid', name='job_remote_type'), nullable=False),
    sa.Column('remote_percentage', sa.Integer(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_type', sa.Enum('hourly', 'monthly', 'yearly', name='job_salary_type'), nullable=True),
    sa.Column('salary_disclosed', sa.Boolean(), nullable=True),
    sa.Column('company_size', sa.Enum('startup', 'small', 'medium', 'large', 'enterprise', name='company_size'), nullable=True),
    sa.Column('company_type', sa.Enum('public', 'private', 'nonprofit', 'government', 'startup', name='company_type'), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_website', sa.String(length=500), nullable=True),
    sa.Column('company_logo_url', sa.String(length=500), nullable=True),
    sa.Column('application_email', sa.String(length=120), nullable=True),
    sa.Column('application_url', sa.String(length=500), nullable=True),
    sa.Column('application_instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'filled', 'expired', 'cancelled', name='job_status'), nullable=False),
    sa.Column('source', sa.Enum('internal', 'linkedin', 'indeed', 'glassdoor', 'workopolis', 'monster', 'other', name='job_source'), nullable=True),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('ai_processed', sa.Boolean(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('match_score_threshold', sa.Float(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('application_count', sa.Integer(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('urgent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_title'), ['title'], unique=False)

    op.create_table('job_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desired_job_titles', sa.JSON(), nullable=True),
    sa.Column('preferred_industries', sa.JSON(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('experience_level', sa.Enum('entry', 'junior', 'mid', 'senior', 'lead', 'executive', name='experience_level'), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('remote_preference', sa.Enum('onsite_only', 'remote_only', 'hybrid_preferred', 'flexible', name='remote_preference'), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=True),
    sa.Column('commute_distance', sa.Integer(), nullable=True),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_type', sa.Enum('hourly', 'monthly', 'yearly', name='salary_type'), nullable=True),
    sa.Column('salary_negotiable', sa.Boolean(), nullable=True),
    sa.Column('employment_types', sa.JSON(), nullable=True),
    sa.Column('contract_duration_min', sa.Integer(), nullable=True),
    sa.Column('contract_duration_max', sa.Integer(), nullable=True),
    sa.Column('company_sizes', sa.JSON(), nullable=True),
    sa.Column('company_types', sa.JSON(), nullable=True),
    sa.Column('preferred_companies', sa.JSON(), nullable=True),
    sa.Column('excluded_companies', sa.JSON(), nullable=True),
    sa.Column('required_benefits', sa.JSON(), nullable=True),
    sa.Column('preferred_benefits', sa.JSON(), nullable=True),
    sa.Column('work_life_balance_priority', sa.Enum('low', 'medium', 'high', 'critical', name='priority_level'), nullable=True),
    sa.Column('job_search_status', sa.Enum('not_searching', 'passively_looking', 'actively_searching', 'urgently_searching', name='search_status'), nullable=True),
    sa.Column('availability', sa.Enum('immediate', 'two_weeks', 'one_month', 'two_months', 'flexible', name='availability'), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), nullable=True),
    sa.Column('push_notifications', sa.Boolean(), nullable=True),
    sa.Column('notification_frequency', sa.Enum('real_time', 'daily', 'weekly', 'bi_weekly', name='notification_frequency'), nullable=True),
    sa.Column('matching_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_apply_enabled', sa.Boolean(), nullable=True),
    sa.Column('match_threshold', sa.Float(), nullable=True),
    sa.Column('profile_visibility', sa.Enum('public', 'recruiter_only', 'private', name='visibility'), nullable=True),
    sa.Column('allow_headhunter_contact', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_job_search_activity', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_type', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('skills_extracted', sa.JSON(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('ats_score', sa.Float(), nullable=True),
    sa.Column('keyword_matches', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('last_viewed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_posting_id', sa.Integer(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('job_url', sa.String(length=500), nullable=True),
    sa.Column('job_board', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('draft', 'applied', 'screening', 'interview_scheduled', 'interviewed', 'offer_received', 'accepted', 'rejected', 'withdrawn', 'no_response', name='application_status'), nullable=False),
    sa.Column('application_method', sa.Enum('manual', 'auto_apply', 'direct', 'referral', name='application_method'), nullable=False),
    sa.Column('recruiter_name', sa.String(length=100), nullable=True),
    sa.Column('recruiter_email', sa.String(length=120), nullable=True),
    sa.Column('hr_contact', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('salary_currency', sa.String(length=10), nullable=True),
    sa.Column('salary_type', sa.Enum('hourly', 'monthly', 'yearly', name='salary_type'), nullable=True),
    sa.Column('job_location', sa.String(length=200), nullable=True),
    sa.Column('remote_type', sa.Enum('onsite', 'remote', 'hybrid', name='remote_type'), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cover_letter_tailored', sa.Boolean(), nullable=True),
    sa.Column('resume_tailored', sa.Boolean(), nullable=True),
    sa.Column('additional_documents', sa.JSON(), nullable=True),
    sa.Column('ai_optimized', sa.Boolean(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('ai_suggestions', sa.JSON(), nullable=True),
    sa.Column('keywords_matched', sa.JSON(), nullable=True),
    sa.Column('application_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('interview_date', sa.DateTime(), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=True),
    sa.Column('response_date', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_table('resumes')
    op.drop_table('job_preferences')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_title'))
        batch_op.drop_index(batch_op.f('ix_job_postings_location'))
        batch_op.drop_index(batch_op.f('ix_job_postings_industry'))
        batch_op.drop_index(batch_op.f('ix_job_postings_expires_at'))
        batch_op.drop_index(batch_op.f('ix_job_postings_created_at'))
        batch_op.drop_index(batch_op.f('ix_job_postings_company_name'))
        batch_op.drop_index(batch_op.f('ix_job_postings_city'))

    op.drop_table('job_postings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
