# Dockerfile.airflow

FROM apache/airflow:2.7.0-python3.8

USER root

# (Optional) Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch back to airflow user before installing Python packages
USER airflow

# Install Python packages
RUN pip install --no-cache-dir \
    pymongo \
    pandas \
    streamlit \
    openai \
    sentence-transformers \
    scikit-learn \
    pyarrow \
    fastparquet \
    google-cloud-aiplatform
